# Generated by Django 6.1 on 2026-09-07 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsource',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.chunk'),
        ),
        migrations.AlterUniqueTogether(
            name='chatsource',
            unique_together={('chat', 'chunk')},
        ),
    ]
